spring:
    application:
      name: lesson
    profiles:
      active: dev
    jpa:
      open-in-view: false
lingosphinx:
  gamification:
    client:
      api-key: ${GAMIFICATION_API_KEY}
      url: ${GAMIFICATION_CLIENT_URL}
  lesson:
    languages: en,de,fr,es,ru,ar-EG,zh