server:
  port: 8083
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:myapp}
    username: ${DB_USER:user}
    password: ${DB_PASSWORD:pass}
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      format_sql: true
      ddl-auto: create-drop
    properties:
      hibernate:
        generate_statistics: true
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
  sql:
    init:
      mode: always
  liquibase:
    enabled: false
cors:
  allowed-origins:
    - http://localhost:5173
    - capacitor://localhost
    - http://localhost
jwt:
  secret: ${JWT_SECRET}
lingosphinx:
  gamification:
    client:
        url: ${GAMIFICATION_CLIENT_URL:http://localhost:8084}